### ISSUE TITLE
How to deploy in vps?

### ISSUE THREAD

**Issue by teamhdt-bsnl** [5hojib/Aeon#124]
Please add config.env and docker file to run this bot in vps

**Comment by 5hojib** [comment]
Why not you add yourself?

**Comment by teamhdt-bsnl** [comment]
I added my myself but getting this error

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/aeon/bot/__init__.py", line 11, in <module>
    from aria2p import API as ariaAPI, Client as ariaClient
ModuleNotFoundError: No module named 'aria2p'

**Comment by ALiENxBEN** [comment]
It's simple I deployed contact @NUMBER03ANURAG

**Comment by teamhdt-bsnl** [comment]
> It's simple I deployed contact @NUMBER03ANURAG

No reply from u. Reply me tg @Sakthi_HDT
