### ISSUE TITLE
Why did you delete dev Branche

### ISSUE THREAD

**Issue by XF2S** [5hojib/Aeon#133]
What the python version you are using or what is will work instead of dev
And thanks for help❤️

**Comment by 5hojib** [comment]
> What the python version you are using or what is will work instead of dev And thanks for help❤️

Previously it was python 3.10 now 3.12

**Comment by XF2S** [comment]
It's have erorr with 3.12

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 440, in <module>
    srun(["xnox", "-d", "--profile=."], check=False)
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xnox'



What should I use it instead of dev 
On dockerfile

This with the error and this is old he working be for since you delete the Branche

This what working befor 

FROM 5hojib/aeon:dev

WORKDIR /usr/src/app
RUN chmod 777 /usr/src/app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .




And this have the error you seen
It 





FROM python:3.10
WORKDIR /usr/src/app
RUN chmod 777 /usr/src/app


COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt --break-system-packages

COPY . .

**Comment by 5hojib** [comment]
You have to must use official Docker of this repo

**Comment by XF2S** [comment]
My dear friend it's working be for you delete dev now not can you do back?
